▸	**Lab 1:  Modelos de redes bayesianas: Naive Bayes.**

**0. Librerias necesarias para el laboratorio.**

In [1]:
import pandas as pd
import numpy as np


%matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.feature_selection import SelectKBest
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

**1. Análisis descriptivo de los datos:**

In [2]:
df = pd.read_csv(r'lab1-dataset.txt')
# X Caracteristicas -> demás columnas
# Y Variable Objetivo -> classname

df.head()

,classname,handicapped-infants,water-project-cost-sharing,adoption-of-the-budget-resolution,physician-fee-freeze,el-salvador-aid,religious-groups-in-schools,anti-satellite-test-ban,aid-to-nicaraguan-contras,mx-missile,immigration,synfuels-corporation-cutback,education-spending,superfund-right-to-sue,crime,duty-free-exports,export-administration-act-south-africa
0,1,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,NaN,1.0,1.0,1.0,0.0,1.0
1,1,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,NaN
2,0,NaN,1.0,1.0,NaN,1.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0
3,0,0.0,1.0,1.0,0.0,NaN,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0
4,0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,NaN,1.0,1.0,1.0,1.0

In [3]:
print(df.groupby('classname').size())

classname
0    267
1    168
dtype: int64

**2. Tratamiento de missing:**

In [4]:
#df.describe()

for col in df.columns:
    df.fillna({col: df[col].mode()[0]}, inplace=True)

**3. Determinar el conjunto de modelización y el de validación.**

Buscamos dividir nuestros datos para que el 75 % de los datos sean para entrenamiento y el 25 % para test.

In [5]:
# Dividir los datos en conjunto de entrenamiento y de test
from sklearn.model_selection import train_test_split

X_train, X_test = train_test_split(df, random_state=2)

# Vemos que se ha realizado correctamente el reparto de los datos.
print("Ejemplos usados para entrenar: ", len(X_train))
print("Ejemplos usados para test: ", len(X_test))

# Asignaremos los valores de classname
y_train = X_train['classname']
y_test = X_test['classname']
print("Distribución de los datos de test:" )
print(X_test['classname'].value_counts(sort=True))

Ejemplos usados para entrenar:  326
Ejemplos usados para test:  109
Distribución de los datos de test:
classname
0    64
1    45
Name: count, dtype: int64

Nos ponemos a entrenar nuestros datos, para ello vamos a utilizar Multinomial Naive Bayes al ser datos discretos.

In [6]:
from sklearn.naive_bayes import MultinomialNB
naive_bayes = MultinomialNB()

X_train.drop(['classname'], axis=1)
naive_bayes.fit(X_train, y_train)

MultinomialNB()

Por último vamos a predecir utilizando los datos test.

In [7]:
X_test.drop(['classname'], axis=1)
predictions = naive_bayes.predict(X_test)

**4. Calcular las métricas de evaluación de ajuste adecuadas.**

In [8]:
reportOriginal = precision_score(y_test, predictions)
print(reportOriginal)

0.9

**5. 	Comentar los resultados obtenidos.**

Realizar una labor de investigación de que métricas de desempeño estan adecuadas a un clasificador.

**6. Otros comentarios que parezcan adecuados.**

**6.1 Cambiar el porcentaje de datos de entrenamiento**

In [19]:
X_train, X_test = train_test_split(df, test_size=0.5, random_state=2)

In [18]:
# Vemos que se ha realizado correctamente el reparto de los datos.
print("Ejemplos usados para entrenar: ", len(X_train))
print("Ejemplos usados para test: ", len(X_test))

# Asignaremos los valores de classname
y_train = X_train['classname']
y_test = X_test['classname']
print("Distribución de los datos de test:" )
print(X_test['classname'].value_counts(sort=True))

Ejemplos usados para entrenar:  217
Ejemplos usados para test:  218
Distribución de los datos de test:
classname
0    136
1     82
Name: count, dtype: int64

**6.2 Utizar Bernoulli modelo en vez Multinomial.**

In [24]:
from sklearn.naive_bayes import BernoulliNB

naive_bayes = BernoulliNB()

In [28]:
X_test.drop(['classname'], axis=1)
naive_bayes.fit(X_train, y_train)
predictions = naive_bayes.predict(X_test)

In [29]:
reportOriginal = precision_score(y_test, predictions)
print(reportOriginal)

0.9166666666666666

**6.3 Borrar datos en vez de sustitución.**

In [33]:
df_borrar = pd.read_csv(r'lab1-dataset.txt')

for col in df_borrar.columns:
    df_borrar.dropna(inplace=True)

df_borrar.count()

classname                                 232
handicapped-infants                       232
water-project-cost-sharing                232
adoption-of-the-budget-resolution         232
physician-fee-freeze                      232
el-salvador-aid                           232
religious-groups-in-schools               232
anti-satellite-test-ban                   232
aid-to-nicaraguan-contras                 232
mx-missile                                232
immigration                               232
synfuels-corporation-cutback              232
education-spending                        232
superfund-right-to-sue                    232
crime                                     232
duty-free-exports                         232
export-administration-act-south-africa    232
dtype: int64